[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
<<<<<<< before updating
name = "mqtt-ingest-pipeline"
version = "0.1.1"
description = "Collection of MQTT data transformers for home automation and IoT devices."
=======
name = "mqtt-ingest-pipelines"
version = "0.1.0"
description = "Collection of MQTT data pipelines for home automation and IoT devices."
>>>>>>> after updating
authors = [
    { name = "stkr22", email = "stkr22@github.com" }
]
readme = "README.md"
license = { text = "GNU General Public License v3.0" }
<<<<<<< before updating
requires-python = ">=3.11,<3.13"
dependencies = [
    "aiomqtt>=2.3",
    "asyncpg>=0.30.0",
    "sqlmodel>=0.0.22",
    "typer>=0.15.0",
]
keywords = ["mqtt", "iot", "home-automation", "timescaledb"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Home Automation",
]

[project.scripts]
mqtt-ingest-pipeline = "mqtt_ingest_pipeline.main:app"

=======

keywords = []
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Topic :: Undefined",
]

requires-python = ">=3.11,<3.13"
dependencies = []

>>>>>>> after updating
[dependency-groups]
dev = [
    "ruff>=0.8.0",
    "mypy>=1.11.0",
    "pytest>=8.3.3",
    "pytest-cov>=6.0.0",
]

[tool.ruff]
target-version = "py312"
line-length = 120
indent-width = 4

[tool.ruff.lint]
select = [
    "E",    # pycodestyle errors
    "F",    # pyflakes
    "I",    # isort
    "UP",   # pyupgrade
    "N",    # pep8-naming
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "RET",  # flake8-return
    "SIM",  # flake8-simplify
    "ARG",  # flake8-unused-arguments
    "PTH",  # flake8-use-pathlib
    "ERA",  # eradicate
]
ignore = ["E203"]

[tool.mypy]
python_version = "3.12"
warn_return_any = true
warn_unused_configs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
addopts = "-ra -q"

[tool.coverage.run]
<<<<<<< before updating
source = ["mqtt_ingest_pipeline"]
=======
source = ["mqtt_ingest_pipelines"]
>>>>>>> after updating
branch = true

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if __name__ == .__main__.:",
]
